import json
import sys
from pathlib import Path
from datetime import datetime, timedelta
import xmlrpc.client

# --- CONFIGURATION ---
ODOO_URL = "http://localhost:8069"
DB_NAME = "AI-Employee"
EMAIL = "ramshashafiq85@gmail.com"
PASSWORD = "ramsha1234"

# Connect to Odoo
common = xmlrpc.client.ServerProxy(f'{ODOO_URL}/xmlrpc/2/common')
models = xmlrpc.client.ServerProxy(f'{ODOO_URL}/xmlrpc/2/object')

def authenticate():
    uid = common.authenticate(DB_NAME, EMAIL, PASSWORD, {})
    if not uid:
        print("Authentication failed!")
        sys.exit(1)
    return uid

def get_weekly_revenue(uid, start_date, end_date):
    """Get revenue for a specific date range"""
    invoice_ids = models.execute_kw(DB_NAME, uid, PASSWORD,
        'account.move', 'search', [[
            ['move_type', '=', 'out_invoice'],
            ['invoice_date', '>=', start_date],
            ['invoice_date', '<=', end_date]
        ]]
    )
    
    if not invoice_ids:
        return {"total": 0, "count": 0, "invoices": []}
    
    invoices = models.execute_kw(DB_NAME, uid, PASSWORD,
        'account.move', 'read', [invoice_ids],
        {'fields': ['id', 'name', 'partner_id', 'amount_total', 'state', 'invoice_date']}
    )
    
    total = sum(i.get('amount_total', 0) for i in invoices if i.get('state') == 'posted')
    return {
        "total": total,
        "count": len(invoices),
        "invoices": invoices
    }

def get_completed_tasks(vault_path, start_date, end_date):
    """Count files moved to Done folder in the date range"""
    done_folder = Path(vault_path) / "Done"
    if not done_folder.exists():
        return []
    
    completed = []
    for f in done_folder.glob("*.md"):
        # Simple check - in production, parse the frontmatter
        completed.append(f.name)
    
    return completed

def get_pending_items(vault_path):
    """Get count of pending items"""
    needs_action = Path(vault_path) / "Needs_Action"
    pending_approval = Path(vault_path) / "Pending_Approval"
    
    return {
        "needs_action": len(list(needs_action.glob("*.md"))) if needs_action.exists() else 0,
        "pending_approval": len(list(pending_approval.glob("*.md"))) if pending_approval.exists() else 0
    }

def generate_briefing(vault_path):
    """Generate the Monday Morning CEO Briefing"""
    uid = authenticate()
    
    # Calculate last week's date range
    today = datetime.now()
    # Find last Monday
    days_since_monday = today.weekday()
    last_monday = today - timedelta(days=days_since_monday + 7)
    last_sunday = last_monday + timedelta(days=6)
    
    start_str = last_monday.strftime("%Y-%m-%d")
    end_str = last_sunday.strftime("%Y-%m-%d")
    
    # Get data
    revenue = get_weekly_revenue(uid, start_str, end_str)
    completed = get_completed_tasks(vault_path, start_str, end_str)
    pending = get_pending_items(vault_path)
    
    # Get business goals
    goals_file = Path(vault_path) / "Business_Goals.md"
    monthly_target = 10000  # Default
    if goals_file.exists():
        content = goals_file.read_text()
        if "Monthly goal: $" in content:
            # Extract target
            for line in content.split("\n"):
                if "Monthly goal:" in line:
                    monthly_target = int(line.split("$")[1].replace(",", ""))
                    break
    
    # Generate briefing
    timestamp = today.strftime("%Y-%m-%dT%H:%M:%S")
    briefing_date = today.strftime("%Y-%m-%d")
    
    mtd_revenue = revenue["total"]  # Simplified - in production, calculate from month start
    progress_pct = (mtd_revenue / monthly_target * 100) if monthly_target > 0 else 0
    
    content = f"""---
generated: {timestamp}
period: {start_str} to {end_str}
---

# Monday Morning CEO Briefing

## Executive Summary
Revenue tracking for the week. {len(completed)} tasks completed. {pending['needs_action']} items pending action.

## Revenue
- **This Week**: ${revenue['total']:,.2f}
- **MTD**: ${mtd_revenue:,.2f}
- **Target**: ${monthly_target:,} ({progress_pct:.0f}%)
- **Invoice Count**: {revenue['count']}

## Completed Tasks
"""
    
    if completed:
        for task in completed[:10]:  # Show last 10
            content += f"- [x] {task}\n"
    else:
        content += "_No completed tasks this week_\n"
    
    content += f"""
## Pending Items
- **Needs Action**: {pending['needs_action']}
- **Pending Approval**: {pending['pending_approval']}

## Proactive Suggestions

### Cost Optimization
- Review subscriptions for unused services
- Check for duplicate tools with overlapping functionality

### Upcoming Deadlines
- Review active projects in Business_Goals.md
- Check invoice payment status in Odoo

---
*Generated by AI Employee v0.1*
"""
    
    # Save briefing
    briefings_dir = Path(vault_path) / "Briefings"
    briefings_dir.mkdir(parents=True, exist_ok=True)
    
    briefing_file = briefings_dir / f"{briefing_date}_Monday_Briefing.md"
    briefing_file.write_text(content)
    
    print(f"\n{'='*50}")
    print(f"CEO BRIEFING GENERATED")
    print(f"File: {briefing_file}")
    print(f"{'='*50}\n")
    print(content)
    
    return str(briefing_file)


if __name__ == "__main__":
    project_root = Path(__file__).parent
    vault_path = project_root / "AI_Employee_Vault"
    
    generate_briefing(str(vault_path))
